config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :inquiries
  resources :responses

  root to: redirect('/inquiries')
  resources :desks

end

app/models/desk.rb
class Desk < ActiveRecord::Base
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #useridを必須・一意とする
  validates_uniqueness_of :userid
  validates_presence_of :userid

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    #before_actionを設定
  before_action :authenticate_user!

  #before_filterを設定
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #strong parametersを設定し、useridを許可
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:userid, :email, :name, :password, :password_confirmation) }
  end
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  before_action :set_desk, only: [:show, :edit, :update, :destroy]

  # GET /desks
  # GET /desks.json
  def index
    @desks = Desk.all
  end

  # GET /desks/1
  # GET /desks/1.json
  def show
  end

  # GET /desks/new
  def new
    @desk = Desk.new
  end

  # GET /desks/1/edit
  def edit
  end

  # POST /desks
  # POST /desks.json
  def create
    @desk = Desk.new(desk_params)

    respond_to do |format|
      if @desk.save
        format.html { redirect_to @desk, notice: 'Desk was successfully created.' }
        format.json { render :show, status: :created, location: @desk }
      else
        format.html { render :new }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desks/1
  # PATCH/PUT /desks/1.json
  def update
    respond_to do |format|
      if @desk.update(desk_params)
        format.html { redirect_to @desk, notice: 'Desk was successfully updated.' }
        format.json { render :show, status: :ok, location: @desk }
      else
        format.html { render :edit }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desks/1
  # DELETE /desks/1.json
  def destroy
    @desk.destroy
    respond_to do |format|
      format.html { redirect_to desks_url, notice: 'Desk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desk
      @desk = Desk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def desk_params
      params.require(:desk).permit(:who, :Q, :date)
    end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to @inquiry, notice: t('messages.inquiry_created') }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: t('messages.inquiry_updated') }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: t('messages.inquiry_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:accepted_datetime, :inquired_person, :contents)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to @response, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:responced_datetime, :user_id, :contents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/desks/_form.html.erb
<%= form_for(@desk) do |f| %>
  <% if @desk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@desk.errors.count, "error") %> prohibited this desk from being saved:</h2>

      <ul>
      <% @desk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :who %><br>
    <%= f.text_field :who %>
  </div>
  <div class="field">
    <%= f.label :Q %><br>
    <%= f.text_area :Q %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/desks/edit.html.erb
<h1>Editing desk</h1>

<%= render 'form' %>

<%= link_to 'Show', @desk %> |
<%= link_to 'Back', desks_path %>

app/views/desks/index.html.erb
<h1>Listing desks（いちらんでっせ）</h1>

<table>
  <thead>
    <tr>
      <th>だれやねん？</th>
      <th>しつもんやねん</th>
      <th>いつやねん</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @desks.each do |desk| %>
      <tr>
        <td><%= desk.who %></td>
        <td><%= desk.Q %></td>
        <td><%= desk.date %></td>
        <td><%= link_to 'みるで', desk %></td>
        <td><%= link_to 'なおしたいねんけど', edit_desk_path(desk) %></td>
        <td><%= link_to 'ですとろーい！！！', desk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'あたらしいしつもん', new_desk_path %>

app/views/desks/new.html.erb
<h1><%= t('views.desk_new_title') %></h1>

<%= render 'form' %>

<%= link_to 'Back', desks_path %>

app/views/desks/show.html.erb
<p>
  <strong><%= t('activerecord.attributes.desk.who') %>:</strong>
  <%= @desk.who %>
</p>

<p>
  <strong><%= t('activerecord.attributes.desk.Q') %>:</strong>
  <%= @desk.Q %>
</p>

<p>
  <strong><%= t('activerecord.attributes.desk.date') %>:</strong>
  <%= @desk.date %>
</p>

<%= link_to 'Edit', edit_desk_path(@desk) %> |
<%= link_to 'Back', desks_path %>

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :accepted_datetime %><br>
    <%= f.datetime_select :accepted_datetime %>
  </div>
  <div class="field">
    <%= f.label :inquired_person %><br>
    <%= f.text_field :inquired_person %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1><%= t('views.inquiry_edit') %></h1>

<%= render 'form' %>

<%= link_to t('views.show'), @inquiry %> |
<%= link_to t('views.back_to_list'), inquiries_path %>

app/views/inquiries/index.html.erb
<h1><%= t('views.inquiries_list') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.inquiry.accepted_datetime') %></th>
      <th><%= t('activerecord.attributes.inquiry.inquired_person') %></th>
      <th><%= t('activerecord.attributes.inquiry.contents') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.accepted_datetime %></td>
        <td><%= inquiry.inquired_person %></td>
        <td><%= inquiry.contents %></td>
        <td><%= link_to t('views.show'), inquiry %></td>
        <td><%= link_to t('views.edit'), edit_inquiry_path(inquiry) %></td>
        <td><%= link_to t('views.destroy'), inquiry, method: :delete, data: { confirm: t('messages.confirm_destroy') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('views.inquiry_create'), new_inquiry_path %>
<br>
<br>

app/views/inquiries/new.html.erb
<h1><%= t('views.inquiry_create') %></h1>

<%= render 'form' %>

<%= link_to t('views.back_to_list'), inquiries_path %>

app/views/inquiries/show.html.erb
<p>
  <strong><%= t('activerecord.attributes.inquiry.accepted_datetime') %>:</strong>
  <%= @inquiry.accepted_datetime %>
</p>

<p>
  <strong><%= t('activerecord.attributes.inquiry.inquired_person') %>:</strong>
  <%= @inquiry.inquired_person %>
</p>

<p>
  <strong><%= t('activerecord.attributes.inquiry.contents') %>:</strong>
  <%= @inquiry.contents %>
</p>

<%= link_to t('views.edit'), edit_inquiry_path(@inquiry) %> |
<%= link_to t('views.back_to_list'), inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelpdeskMgt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">HelpdeskMgt</a>
      </div>
      <div class="collapse navbar-collapse">
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to '問い合わせ', inquiries_path %></li>
          <li><%= link_to '回答', responses_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
      </ul>
        <% end %>

      </div>
    </div>
  </nav>


  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      Helpdesk-mgt 2014
    </div>
  </footer>
  <script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :responced_datetime %><br>
    <%= f.datetime_select :responced_datetime %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1><%= t('views.response_edit') %></h1>

<%= render 'form' %>

<%= link_to t('views.show'), @response %> |
<%= link_to t('views.back_to_list'), responses_path %>

app/views/responses/index.html.erb
<h1><%= t('views.responses_list') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.response.responced_datetime') %></th>
      <th><%= t('activerecord.attributes.response.user_id') %></th>
      <th><%= t('activerecord.attributes.response.contents') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.responced_datetime %></td>
        <td><%= response.user %></td>
        <td><%= response.contents %></td>
        <td><%= link_to t('views.show'), response %></td>
        <td><%= link_to t('views.edit'), edit_response_path(response) %></td>
        <td><%= link_to t('views.destroy'), response, method: :delete, data: { confirm: t('messages.confirm_destroy') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('views.response_create'), new_response_path %>

app/views/responses/new.html.erb
<h1><%= t('views.response_create') %></h1>

<%= render 'form' %>

<%= link_to t('views.back_to_list'), responses_path %>

app/views/responses/show.html.erb
<p>
  <strong><%= t('activerecord.attributes.response.responced_datetime') %>:</strong>
  <%= @response.responced_datetime %>
</p>

<p>
  <strong><%= t('activerecord.attributes.response.user') %>:</strong>
  <%= @response.user %>
</p>

<p>
  <strong><%= t('activerecord.attributes.response.contents') %>:</strong>
  <%= @response.contents %>
</p>

<%= link_to t('views.edit'), edit_response_path(@response) %> |
<%= link_to t('views.back_to_list'), responses_path %>